# Generated by Django 4.1.5 on 2023-03-11 11:20

import datetime
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_topic_options_field_slug_topic_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['category', 'topic']),
        ),
        migrations.AlterField(
            model_name='topic',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2023, 3, 11, 11, 20, 9, 533789)),
        ),
    ]
