# Generated by Django 4.1.5 on 2023-03-13 21:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_rename_response_responses_alter_topic_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response', to='chat.topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2023, 3, 13, 21, 27, 59, 660006)),
        ),
    ]
