# Generated by Django 4.1.5 on 2023-03-14 05:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_responses_topic_alter_topic_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='category',
            field=models.CharField(choices=[('science', 'science'), ('social', 'social'), ('law', 'law'), ('spiritual', 'spiritual')], default='any', max_length=200),
        ),
        migrations.AlterField(
            model_name='topic',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2023, 3, 14, 5, 24, 11, 345729)),
        ),
    ]
