# Generated by Django 4.1.5 on 2023-03-14 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_like_dislikes_like_likes_like_loves_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2023, 3, 14, 13, 59, 28, 168973)),
        ),
    ]
