# Generated by Django 4.1.5 on 2023-03-15 09:16

import chat.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_like_participants_alter_topic_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='load_pic',
            field=models.ImageField(blank=True, null=True, upload_to=chat.models.upload_to, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2023, 3, 15, 9, 16, 4, 257660)),
        ),
    ]
